models:
  llm:
    Llama3 70b:
      model_id: "meta.llama3-70b-instruct-v1:0"
      temperature: 0.5
      top_p: 1.0
      #top_k: 500   not supported by Llama3
      #max_tokens: 4096   not supported by Llama3
      memory_window: 3
      max_top_k: 500
      model_region: us-west-2
    Claude 3.5 Sonnet v2:
      model_id: "anthropic.claude-3-5-sonnet-20241022-v2:0"
      temperature: 0.1
      top_p: 1.0
      top_k: 500
      max_tokens: 4096
      memory_window: 10
      max_top_k: 500
      model_region: us-west-2
    Claude 3.5 Haiku:
      model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"
      temperature: 0.1
      top_p: 1.0
      top_k: 500
      max_tokens: 4096
      memory_window: 10
      max_top_k: 500
      model_region: us-west-2
    OpenAI GPT 4o:
      model_id: "gpt-4o"
      temperature: 0.5
      top_p: 1.0
      top_k: 500
      max_tokens: 4096
      memory_window: 3
      max_top_k: 500
      model_region: us-west-2
      model_endpoint: "/healthcheck/api-endpoint/gpt-4o"
      model_api_key: "/healthcheck/api-key/openai/gpt-4o"
      model_deployment_name: gpt-4o

    OpenAI GPT 4o Realtime Preview:
      model_id: "gpt-4o-realtime-preview"
      temperature: 0.5
      top_p: 1.0
      top_k: 500
      max_tokens: 4096
      memory_window: 3
      max_top_k: 500
      model_region: us-west-2
      model_endpoint:  "/healthcheck/api-endpoint/gpt-4o-realtime-preview"
      model_api_key:  "/healthcheck/api-key/openai/gpt-4o-realtime-preview"
      model_deployment_name: gpt-4o-realtime-preview

    OpenAI GPT o1:
      model_id: "gpt-o1"
      temperature: 0.5
      top_p: 1.0
      top_k: 500
      max_tokens: 4096
      memory_window: 3
      max_top_k: 500
      model_region: us-west-2
      model_endpoint:  "/healthcheck/api-endpoint/gpt-o1"
      model_api_key:  "/healthcheck/api-key/gpt-01"
      model_deployment_name: o1-preview
    #default: Claude 3.5 Haiku
    #default: OpenAI GPT 4o Realtime Preview
    default: OpenAI GPT 4o 

  embedding:
    Cohere Embed English V3:
      model_id: "cohere.embed-english-v3"
      model_region: us-west-2
    default: Cohere Embed English V3
  rerank:
    Cohere Rerank English V3:
      model_id: 'rerank-english-v3.0'
      model_region: us-west-2
    default: Cohere Rerank English V3
nutrition:
  - name
  - food group
  - serving size
  - calories
  - total fat
  - saturated fat
  - trans fat
  - carbohydrates
  - fiber
  - sugars
  - protein
  - cholesterol
  - sodium
database: 
  name: nutrition_data
openai:
  api_key: ${AZURE_OPENAI_API_KEY}
